# Generated by Django 4.0.2 on 2022-02-28 17:31

import arike.users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_user_role'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', arike.users.models.CustomUserManager()),
            ],
        ),
    ]
