# Generated by Django 4.0.2 on 2022-02-20 15:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('System', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('kind', models.IntegerField(choices=[(1, 'PHC'), (2, 'CHC')])),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('pincode', models.CharField(max_length=6)),
                ('phone', models.CharField(max_length=10)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='System.ward')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
