# Generated by Django 4.0.2 on 2022-02-23 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facility', '0003_alter_facility_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
