# Generated by Django 4.0.2 on 2022-02-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0002_patient_facility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
