# Generated by Django 4.0.2 on 2022-02-25 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Patient", "0003_patient_age"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="age",
        ),
    ]
