# Generated by Django 4.0.2 on 2022-02-25 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Patient", "0004_remove_patient_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="address",
            field=models.TextField(),
        ),
    ]
