# Generated by Django 4.0.2 on 2022-02-27 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Patient", "0009_rename_icd_code_disease_icds_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disease",
            name="icds_code",
            field=models.CharField(max_length=25),
        ),
    ]
