# Generated by Django 4.0.2 on 2022-02-27 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Patient", "0010_alter_disease_icds_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="treatment",
            name="care_sub_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="treatment",
            name="care_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="treatment",
            name="description",
            field=models.TextField(),
        ),
    ]
