# Generated by Django 4.0.2 on 2022-02-28 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Patient", "0019_alter_visitdetail_palliative_phase_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="visitdetail",
            name="symptoms",
        ),
        migrations.DeleteModel(
            name="Symptoms",
        ),
    ]
