# Generated by Django 4.0.2 on 2022-02-28 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0020_remove_visitdetail_symptoms_delete_symptoms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitdetail',
            name='mouth_hygiene',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitdetail',
            name='personal_hygiene',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitdetail',
            name='public_hygiene',
            field=models.TextField(blank=True, null=True),
        ),
    ]
